### ISSUE TITLE
Always shows 5 star

### ISSUE THREAD

**Issue by azzazkhan** [ibrahimBougaoua/filament-rating-star#6] opened 2023-09-16 16:18 UTC
### What happened?

I displayed an unsigned short int column in the table using the `RatingStarColumn` but it always shows five stars even though the value for that column is always between 1 and 5 (inclusive).

### How to reproduce the bug

Link an unsigned short int column whose value is between 1 and 5 in the table builder using the `RatingStarColumn` column.

### Package Version

0.0.1

### PHP Version

8.1.23

### Laravel Version

10.10

### Which operating systems does with happen with?

Linux

### Notes

Using Ubuntu through WSL

**Comment by Falki141** [comment] 2023-12-05 16:46
The issue is fixed in main branch, do you can made a new release? :)

**Closed as completed** 2024-02-02 18:06 UTC
Labels: bug

**Comment by abbasmashaddy72** [comment] 2024-02-05 21:11
RatingStarColumn is now showing 2 starts where I have 4 in DB

DB:
|id|title|image_id|rating|video_link|status|excerpt|published_at|deleted_at|created_at|updated_at|
|--|-----|--------|------|----------|------|-------|------------|----------|----------|----------|
|1|{"en":"title"}|17|4||Published|{"en":"Excerpt"}|2024-02-06||2024-02-06 02:29:00.000|2024-02-06 02:29:00.000|

Issue Image
![image](https://github.com/ibrahimBougaoua/filament-rating-star/assets/55267488/26097bd9-31df-4f2d-b636-dc533d13faf7)

@Falki141 @ibrahimBougaoua

**Comment by abbasmashaddy72** [comment] 2024-02-08 18:12
> RatingStarColumn is now showing 2 starts where I have 4 in DB
> 
> DB:
> id 	title 	image_id 	rating 	video_link 	status 	excerpt 	published_at 	deleted_at 	created_at 	updated_at
> 1 	{"en":"title"} 	17 	4 		Published 	{"en":"Excerpt"} 	2024-02-06 		2024-02-06 02:29:00.000 	2024-02-06 02:29:00.000
> 
> Issue Image ![image](https://private-user-images.githubusercontent.com/55267488/302429309-26097bd9-31df-4f2d-b636-dc533d13faf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MTU0OTUsIm5iZiI6MTcwNzQxNTE5NSwicGF0aCI6Ii81NTI2NzQ4OC8zMDI0MjkzMDktMjYwOTdiZDktMzFkZi00ZjJkLWI2MzYtZGM1MzNkMTNmYWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE3NTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmOGJlM2E3NzcyYzE3NTgyZDRlNmMxZjc4YWJiYWJiM2IxMmNlMmJmOWE0NzQ5ODRkNDczNmI4ZTA2M2JhOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0dwaDaqHoPqgTzG6Taf7TByJbfpDTtOXscIw1qJuIYU)
> 
> @Falki141 @ibrahimBougaoua

For 5 Stars it is showing 1
